split data intou 2

In [3]:
import pandas as pd

In [5]:
import botometer

rapidapi_key = "32d259caa4msh1d28e111b7320b3p13c365jsn290859214dbc"

consumer_key="tH7AnhdvgOndxvZOyeeyfHOVG"
consumer_secret="14mR3PZn3osH1OBPjtJWJT7IycQB5kOF4PmIuDjHvFHuEZppk0"
twitter_app_auth = {
    'consumer_key':consumer_key,
    'consumer_secret':consumer_secret ,   
  }
bom = botometer.Botometer(wait_on_ratelimit=True,
                          rapidapi_key=rapidapi_key,
                          **twitter_app_auth)

# Check a single account by screen name
result = bom.check_account('@TrollFootball')

english_score = result['cap']['english']
universal_score = result['cap']['universal']
general_score =5 -((english_score + universal_score) / 2)

{'cap': {'english': 0.7470839770895665, 'universal': 0.8052176344738626}, 'display_scores': {'english': {'astroturf': 0.4, 'fake_follower': 1.6, 'financial': 0.0, 'other': 2.9, 'overall': 1.2, 'self_declared': 0.2, 'spammer': 0.1}, 'universal': {'astroturf': 0.4, 'fake_follower': 0.8, 'financial': 0.2, 'other': 3.2, 'overall': 3.2, 'self_declared': 0.2, 'spammer': 0.1}}, 'raw_scores': {'english': {'astroturf': 0.07, 'fake_follower': 0.33, 'financial': 0.01, 'other': 0.58, 'overall': 0.25, 'self_declared': 0.05, 'spammer': 0.02}, 'universal': {'astroturf': 0.07, 'fake_follower': 0.15, 'financial': 0.03, 'other': 0.63, 'overall': 0.63, 'self_declared': 0.05, 'spammer': 0.02}}, 'user': {'majority_lang': 'en', 'user_data': {'id_str': '571964518', 'screen_name': 'TrollFootball'}}}

In [6]:
result = bom.check_account('@the_kingslife')

# Check a single account by id
# result = bom.check_account(1548959833)
print(result)

{'cap': {'english': 0.7907586934369296, 'universal': 0.8115094045580712}, 'display_scores': {'english': {'astroturf': 0.2, 'fake_follower': 1.1, 'financial': 0.0, 'other': 3.2, 'overall': 1.8, 'self_declared': 3.2, 'spammer': 0.7}, 'universal': {'astroturf': 0.1, 'fake_follower': 1.1, 'financial': 0.0, 'other': 3.8, 'overall': 3.8, 'self_declared': 3.2, 'spammer': 0.7}}, 'raw_scores': {'english': {'astroturf': 0.04, 'fake_follower': 0.22, 'financial': 0.01, 'other': 0.64, 'overall': 0.36, 'self_declared': 0.63, 'spammer': 0.14}, 'universal': {'astroturf': 0.02, 'fake_follower': 0.22, 'financial': 0.01, 'other': 0.76, 'overall': 0.76, 'self_declared': 0.65, 'spammer': 0.14}}, 'user': {'majority_lang': 'en', 'user_data': {'id_str': '1585621392573317122', 'screen_name': 'the_kingslife'}}}

In [7]:

# read DataFrame
df = pd.read_csv("./Data/cleandatafromAPI.csv")

In [2]:
k = 2
size = 17023
data = pd.read_csv("./Data/cleandatafromAPI.csv")
for i in range(k):
    df = data[size*i:size*(i+1)]
    df.to_csv(f'data{i+1}.csv', index=False)
consumer_key1= 'txGKpZibczbB3viciPGaIht1h'
consumer_secret1= 'LdBcAwDspNV2IoGdBrDC5wTiprqW4LiHPFTOWcq95a9FgkWc5M'
access_token1= '1622613622860967937-HtuI8jqgHy8P5fJgN1EKGLqqDqWCOw'
access_token_secret1= 'uEpId3rtrIdNZe9iylsohsu7xvoMHs8NHgfNOndfgh6Me'
bearer_token1="AAAAAAAAAAAAAAAAAAAAAJ%2BwlgEAAAAAApXZ%2BQkCOMMCUz8yA0Q2U7cIx4A%3D54C8m6MSpNmM1g4oeEH5ZpzknYFfJ4zYSWSaxVteTpfofyg5Ni"
rapidapi_key1 ="99ba8c7fcemshe47fdb473278300p152fa7jsn2a114ad217c5"

In [13]:
df

,image,background_image,verified,statuses,screen_name,display_name,description,location,url,date_joined,...,lists,twitter_user_id,tweet_language,tweets_this_week,retweet_ratio,retweeted_count,tweets_by_day_of_week,tweets_by_hour_of_day,account_type,fake_follower
0,https://pbs.twimg.com/profile_images/145899544...,http://abs.twimg.com/images/themes/theme11/bg.gif,False,7098,paty_castroo,Patrcia Castro,NaN,Maring Brasil,NaN,2009-07-04 22:41:51,...,2,53779179,NaN,0.0,0.0,0.0,"[0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",bot,4.167006
1,https://pbs.twimg.com/profile_images/632916759...,http://abs.twimg.com/images/themes/theme3/bg.gif,False,270,CBirckner,Carli Birckner,television producer emmy award winner disney e...,Baltimore MD,NaN,2010-01-17 22:54:19,...,2,105916557,en,0.0,16.0,103418.0,"[9, 4, 12, 15, 5, 0, 3]","[1, 4, 5, 0, 1, 0, 1, 1, 0, 0, 4, 0, 0, 0, 3, ...",human,2.494738
2,https://pbs.twimg.com/profile_images/158696080...,http://abs.twimg.com/images/themes/theme1/bg.png,False,14302,amf_jay,JD,self discovery,NaN,NaN,2012-03-01 06:05:32,...,2,509788597,en,0.0,77.0,867392.0,"[52, 14, 19, 24, 24, 29, 32]","[25, 15, 9, 20, 6, 10, 2, 9, 1, 1, 3, 0, 3, 1,...",human,2.494738
3,https://pbs.twimg.com/profile_images/977012905...,http://abs.twimg.com/images/themes/theme6/bg.gif,False,4585,SaraCavolo,Sara Cavolo,NaN,Brooklyn NY,NaN,2009-09-01 04:52:30,...,3,70601327,en,0.0,54.0,2996382.0,"[19, 34, 42, 41, 28, 17, 15]","[10, 17, 18, 5, 1, 0, 0, 0, 1, 0, 1, 2, 7, 18,...",human,2.494738
4,https://pbs.twimg.com/profile_images/668449819...,http://abs.twimg.com/images/themes/theme14/bg.gif,True,15851,DavidHenaoModel,David Henao,productor televisin embajador contacto dreamco...,Miami FL,https://t.co/KPAyvqMibx,2010-01-27 17:17:23,...,172,108999927,und,0.0,10.0,66477.0,"[33, 23, 25, 24, 34, 28, 33]","[7, 17, 5, 3, 1, 0, 0, 2, 0, 0, 2, 6, 14, 14, ...",human,2.494738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34039,https://pbs.twimg.com/profile_images/712018970...,http://abs.twimg.com/images/themes/theme14/bg.gif,True,60100,AshAlexiss,Ashley Alexiss,self made plus model siswim world traveler,Los Angeles CA,https://t.co/7nNQF782OV,2010-12-07 08:11:16,...,876,223764929,en,8.0,47.0,1375535.0,"[28, 33, 25, 31, 22, 28, 33]","[7, 18, 13, 13, 16, 9, 6, 12, 6, 5, 1, 0, 0, 1...",human,2.494738
34040,https://pbs.twimg.com/profile_images/141825399...,http://abs.twimg.com/images/themes/theme9/bg.gif,True,40277,ahmemis,Ahmet Memi,gazetecijournalist,NaN,https://t.co/0wll8Iymf4,2010-12-04 13:17:22,...,182,222789645,tr,0.0,0.0,15350.0,"[21, 67, 36, 18, 22, 18, 18]","[5, 0, 0, 0, 0, 1, 0, 2, 1, 6, 7, 9, 3, 7, 4, ...",human,2.494738
34041,https://pbs.twimg.com/profile_images/142309872...,http://abs.twimg.com/images/themes/theme10/bg.gif,False,6679,Yuvannamontalvo,Yuvanna Montalvo,modelo actriz venezolana venezuelan model actr...,NaN,NaN,2009-10-06 23:53:30,...,372,80438218,zxx,0.0,8.0,18899.0,"[25, 23, 26, 42, 29, 31, 24]","[23, 26, 21, 8, 1, 2, 0, 0, 0, 2, 0, 0, 4, 10,...",human,2.494738
34042,https://pbs.twimg.com/profile_images/157735786...,http://abs.twimg.com/images/themes/theme1/bg.png,True,2580,IAmVarunTej,Varun Tej Konidela,indianactorneed,Hyderabad,https://t.co/kJoeCCukod,2013-03-24 21:04:16,...,378,1296642259,en,1.0,4.0,145792.0,"[23, 22, 20, 85, 20, 14, 16]","[0, 2, 1, 26, 25, 17, 9, 7, 7, 7, 12, 5, 24, 6...",human,2.494738
34043,https://pbs.twimg.com/profile_images/160574287...,http://abs.twimg.com/images/themes/theme11/bg.gif,False,3566,tiagopoeta,Tiago Poeta,poeta autor escritor acadmico dois livros publ...,NaN,https://t.co/Wu7BylmZN9,2012-06-08 18:51:31,...,25,602979254,pt,14.0,52.0,1771.0,"[18, 35, 20, 12, 33, 54, 24]","[6, 4, 16, 1, 0, 0, 0, 0, 1, 1, 6, 4, 3, 18, 1...",human,2.494738